title: "AITL Controller A-Type"
description: "Educational project for implementing and analyzing the AITL Controller A-Type architecture."
lang: en

url: "https://samizo-aitl.github.io"
baseurl: "/aitl-controller-a-type"

theme: ""   # Minima を完全に無効化

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
