title: "mems-ana"
description: "Lightweight MEMS structural analysis tools (pre-FEM)."
lang: en

url: "https://samizo-aitl.github.io"
baseurl: "/mems-ana"

theme: ""   # Minima を完全に無効化

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
